"""Extracts declared-application fields from a filled-in TTB F 5100.31 PDF.

Reads AcroForm field values directly (no OCR/vision model involved) — this
only works for a PDF that still has its fillable form fields intact, e.g. one
filled out in Acrobat and saved, not a scanned/flattened copy. Field names
below match the official form at https://www.ttb.gov/forms/f510031.pdf; a PDF
generated by other tooling with different field names will simply come back
with nothing mapped.

Note the real form doesn't carry every field ``ApplicationIn`` needs —
class/type designation, ABV, net contents, country of origin, and sulfite
declaration aren't on the application at all in the real-world TTB workflow
(they live only on the label). Those are intentionally absent here, not a
gap in the mapping.
"""

from __future__ import annotations

import io

from pypdf import PdfReader
from pypdf.errors import PdfReadError

from app.data.ttb_rules import BeverageClass


class ApplicationPdfError(Exception):
    """The PDF couldn't be read, or has no fillable form fields to extract."""


_TEXT_FIELD_TARGETS: dict[str, str] = {
    "6. BRAND NAME (Required)": "brand_name",
    "7. FANCIFUL NAME (If any)": "fanciful_name",
    "8. NAME AND ADDRESS OF APPLICANT AS SHOWN ON PLANT REGISTRY, BASIC": "name_address",
    "11.  WINE APPELLATION (If on label)": "appellation",
}

_CHECKBOX_FIELD_TARGETS: dict[str, tuple[str, dict[str, object]]] = {
    "Check Box22": (
        "beverage_class",
        {"Wine": BeverageClass.WINE, "Spirits": BeverageClass.DISTILLED_SPIRITS, "Malt": BeverageClass.MALT_BEVERAGE},
    ),
    "Check Box34": ("imported", {"Domes": False, "Import": True}),
}


def extract_application_pdf_fields(pdf_bytes: bytes) -> dict[str, object]:
    """Returns a partial dict of ``ApplicationIn``-shaped fields found in the
    PDF's form fields. Only keys with a value TTB's form actually captures
    are present; the caller merges this into whatever the user has already
    entered rather than treating it as a complete application."""

    try:
        reader = PdfReader(io.BytesIO(pdf_bytes))
        fields = reader.get_fields()
    except PdfReadError as exc:
        raise ApplicationPdfError("Couldn't read that file as a PDF.") from exc

    if not fields:
        raise ApplicationPdfError(
            "This PDF has no fillable form fields to read — it may be a scanned or flattened copy. "
            "Please fill in the application fields manually."
        )

    result: dict[str, object] = {}

    for pdf_field_name, target in _TEXT_FIELD_TARGETS.items():
        value = _clean_text(fields.get(pdf_field_name, {}).get("/V"))
        if value:
            result[target] = value

    for pdf_field_name, (target, export_values) in _CHECKBOX_FIELD_TARGETS.items():
        value = export_values.get(_export_value(fields.get(pdf_field_name, {})))
        if value is not None:
            result[target] = value

    return result


def _clean_text(value: object) -> str | None:
    if not value:
        return None
    text = str(value).replace("\r\n", "\n").replace("\r", "\n").strip()
    return text or None


def _export_value(field: object) -> str | None:
    if not isinstance(field, dict):
        return None
    value = field.get("/V")
    return str(value).lstrip("/") if value else None
